#!/bin/sh

tag="0.1"
image_name="cplusplus-dev-base"

# --name=$USER 方便区分docker container, 否则container的名字将是随机的

#sudo docker run -d --name=${USER} --net=host -u `id -u`:`id -g` -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow -v /etc/group:/etc/group -v ${HOME}:${HOME} -w `pwd` -it ${image_name}:${tag}   /bin/bash
#docker run -d --name=${USER} --net=host -u "admin" -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow -v /etc/group:/etc/group -v ${HOME}:${HOME} -w `pwd` -it ${image_name}:${tag}   /bin/bash

docker run -d --name=graph_engine_dev --net=host  --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v /work/15-project_pdd:/root/project -v /work/16-workspace:/root/workspace  -w /root/ -it ${image_name}:${tag}   /bin/bash